Repository pyswmm/Stormwater-Management-Model, pull requests merged in 2018-03, with the labels that each got.

#155 Feature unittest
  .travis.yml
  CMakeLists.txt
  appveyor.yml
  tests/CMakeLists.txt
  tests/data/Example1.out
  tests/test_output.cpp
  tools/requirements.txt
  tools/run-nrtest.cmd
  tools/swmm-output/CMakeLists.txt
  tools/swmm-output/include/swmm_output.h
  tools/swmm-output/setup.py
  tools/swmm-output/src/swmm_output.c
  tools/swmm-output/test/data/__init__.py
  tools/swmm-output/test/swmm_output_test.py
  tools/swmm-output/test/test_swmm_output.cpp
Labels: type:tech-debt

#162 Fix Regression Tests
  src/node.c
  src/routing.c
  tests/swmm-nrtestsuite/benchmark/swmm-5112/Example_1/Example1.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/Example_2/Example2.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/Example_3/Example3.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/Example_4/Example4.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/Example_5/Example5.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/Example_6/Example6.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_1/extran1.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_10/extran10.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_2/extran2.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_3/extran3.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_4/extran4.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_5/extran5.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_6/extran6.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_7/extran7.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_8a/extran8a.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_8b/extran8b.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/extran_9/extran9.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/test_1/test1.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/test_2/test2.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/test_3/test3.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/test_4/test4.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/test_5/test5.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/user_1/user1.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/user_2/user2.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/user_3/user3.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/user_4/user4.rpt
  tests/swmm-nrtestsuite/benchmark/swmm-5112/user_5/user5.rpt
  tests/swmm-nrtestsuite/tests/examples/Example1.inp
  tests/swmm-nrtestsuite/tests/examples/Example2.inp
  tests/swmm-nrtestsuite/tests/examples/Example3.inp
  tests/swmm-nrtestsuite/tests/examples/Example4.inp
  tests/swmm-nrtestsuite/tests/examples/Example5.inp
  tests/swmm-nrtestsuite/tests/examples/Example6.inp
  tests/swmm-nrtestsuite/tests/extran/extran1.inp
  tests/swmm-nrtestsuite/tests/extran/extran10.inp
  tests/swmm-nrtestsuite/tests/extran/extran2.inp
  tests/swmm-nrtestsuite/tests/extran/extran3.inp
  tests/swmm-nrtestsuite/tests/extran/extran4.inp
  tests/swmm-nrtestsuite/tests/extran/extran5.inp
  tests/swmm-nrtestsuite/tests/extran/extran6.inp
  tests/swmm-nrtestsuite/tests/extran/extran7.inp
  tests/swmm-nrtestsuite/tests/extran/extran8a.inp
  tests/swmm-nrtestsuite/tests/extran/extran8b.inp
  tests/swmm-nrtestsuite/tests/extran/extran9.inp
  tests/swmm-nrtestsuite/tests/routing/test1.inp
  tests/swmm-nrtestsuite/tests/routing/test2.inp
  tests/swmm-nrtestsuite/tests/routing/test3.inp
  tests/swmm-nrtestsuite/tests/routing/test4.inp
  tests/swmm-nrtestsuite/tests/routing/test5.inp
  tests/swmm-nrtestsuite/tests/user/user1.inp
  tests/swmm-nrtestsuite/tests/user/user2.inp
  tests/swmm-nrtestsuite/tests/user/user3.inp
  tests/swmm-nrtestsuite/tests/user/user4.inp
  tests/swmm-nrtestsuite/tests/user/user5.inp
Labels: High Priority, type:task

#136 Adding Rain Gage API
  include/toolkitAPI.h
  src/enums.h
  src/gage.c
  src/objects.h
  src/runoff.c
  src/swmm5.c
  src/toolkitAPI.c
Labels: type:enhancement

#166 AppVeyor: Decouple swmm-output python extension build from main project
  appveyor.yml
  tools/nrtest-swmm/setup.py
  tools/requirements-appveyor.txt
  tools/swmm-output/setup.py
Labels: reso:completed, type:task

#167 Fixes rainfall API
  src/gage.c
  src/toolkitAPI.c
Labels: High Priority, type:bug
