Repository pyswmm/Stormwater-Management-Model, pull requests merged in 2019-05, with the labels that each got.

#236 Add support for LID API
  AUTHORS
  include/toolkitAPI.h
  src/error.c
  src/error.h
  src/headers.h
  src/lid.c
  src/lid.h
  src/lidproc.c
  src/toolkitAPI.c
  tests/data/lid/revised/w_wo_BC_2Subcatchments_revised.inp
  tests/data/lid/revised/w_wo_GR_2Subcatchments_revised.inp
  tests/data/lid/revised/w_wo_IT_2Subcatchments_revised.inp
  tests/data/lid/revised/w_wo_PP_2Subcatchments_revised.inp
  tests/data/lid/revised/w_wo_RB_2Subcatchments_revised.inp
  tests/data/lid/revised/w_wo_RD_2Subcatchments_revised.inp
  tests/data/lid/revised/w_wo_RG_2Subcatchments_revised.inp
  tests/data/lid/revised/w_wo_SWALE_2Subcatchments_revised.inp
  tests/data/lid/w_wo_BC_2Subcatchments.inp
  tests/data/lid/w_wo_GR_2Subcatchments.inp
  tests/data/lid/w_wo_IT_2Subcatchments.inp
  tests/data/lid/w_wo_PP_2Subcatchments.inp
  tests/data/lid/w_wo_RB_2Subcatchments.inp
  tests/data/lid/w_wo_RD_2Subcatchments.inp
  tests/data/lid/w_wo_RG_2Subcatchments.inp
  tests/data/lid/w_wo_SWALE_2Subcatchments.inp
  tests/data/lid/wq_w_wo_RG_2Subcatchments.inp
  tests/test_toolkitapi_lid.cpp
  tests/test_toolkitapi_lid.hpp
  tests/test_toolkitapi_lid_results.cpp
Labels: type:enhancement

#237 Fixed Error return codes to external values
  docs/AUTHORS.dox
  docs/Doxyfile
  include/toolkitAPI.h
  src/error.c
  src/error.h
  src/toolkitAPI.c
  tests/test_swmm.cpp
  tests/test_toolkitapi.cpp
  tests/test_toolkitapi.hpp
  tests/test_toolkitapi_gage.cpp
  tests/test_toolkitapi_lid.cpp
  tests/test_toolkitapi_lid.hpp
  tests/test_toolkitapi_lid_results.cpp
  tests/test_toolkitapi_pollut.cpp
Labels: Easy, type:bug, type:enhancement, type:tech-debt

#216 Api simtime
  include/toolkitAPI.h
  src/toolkitAPI.c
  tests/test_toolkitapi.cpp
Labels: Easy, type:enhancement
